// src/app/forgot/forgot.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { FormBuilder } from '@angular/forms';

@Component({
  selector: 'app-forgot',
  templateUrl: './forgot.component.html',
  styleUrls: ['./forgot.component.css']
})
export class ForgotComponent implements OnInit {

  form;
  errorMessage;
  email;
  password;

  constructor(
    private router: Router,
    private formBuilder: FormBuilder
  ) {
    this.email = localStorage.getItem('email');
    this.password = localStorage.getItem('password');

    this.form = this.formBuilder.group({
      email: ''
    })
   }

  ngOnInit(): void {
    if (this.email !== null && this.password !== null) {
      this.router.navigateByUrl('/profile');
    }
  }

  goToLogin() {
    this.router.navigate(['/']);
  }


  onSubmit(customerData) {

    this.email = customerData.email.trim();

    const that = this;
    fetch(
      "http://localhost:8080/forgot-password",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded"
        },
        body: "email=" + this.email
      }
    ).then(async function(data) {
      data.json().then(async function(data) {
        if (data.message === "Reset password is sent") {
          that.errorMessage = "Password reset link is sent to your email.";
        } else {
          that.errorMessage =  data.message;
        }
      });
    });
  }

}

<h2>Friends</h2>
<h3>Forgot Password</h3>
 
 <form [formGroup]="form" (ngSubmit)="onSubmit(form.value)">

   <div>
    <label for="email">
       Email
    </label>
    <input id="email" type="email" formControlName="email">
  </div>

   <button class="button" type="submit">FORGOT</button>
 
 </form>
 <button (click)="goToLogin()">Cancel</button>

 <div>
 {{errorMessage}}
 </div>

// src/components/Forgot.vue
<template>
<div>
<h2>Friends</h2>
<h3>Forgot Password</h3>

<form id="app" @submit="onSubmit">
  
  <p>
    <label for="email">Email</label>
    <input type="email" name="email" id="email" v-model="email">
  </p>

  <p>
    <input type="submit" value="FORGOT">  
  </p>

</form>
 <button v-on:click="goToLogin">Cancel</button>

<div>
 {{errorMessage}}
</div>

</div>
</template>

<script>

export default {
  name: 'Forgot',
    data() {
    return {
      errorMessage: null,
      email:""
    }
  },
  mounted: function () {

    this.email = localStorage.getItem('email')


    if (this.email != null) {
        this.$router.push('/profile')
    }
},
  methods: {
    goToLogin: function() {
      this.$router.push('/')
    },
    onSubmit:function(e) {

        e.preventDefault();

        const that = this;
        fetch(
        "http://localhost:8080/forgot-password",
        {
            method: "POST",
            headers: {
            "Content-Type": "application/x-www-form-urlencoded"
            },
            body: "email=" + this.email
        }
        ).then(async function(data) {
            data.json().then(async function(data) {
                if (data.message === "Reset password is sent") {
                that.errorMessage = "Password reset link is sent to your email.";
                } else {
                that.errorMessage =  data.message;
                }
            });
        });
    }
  }
}
</script>
