// src/app/profile/profile.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Router, ActivatedRoute, ParamMap, NavigationStart } from '@angular/router';
import { FormBuilder } from '@angular/forms';

import { filter } from 'rxjs/operators';

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.css']
})
export class ProfileComponent implements OnInit {

  email;
  password;
  errorMessage;
  usersAll;
  msgsAll;
  form;

  constructor(
    private router: Router,
    private formBuilder: FormBuilder
  ) { 

  this.form = this.formBuilder.group({
    toEmail: '',
    toMessage: ''
  })
  

  // this.email = window.history.state.email;
  // this.password = window.history.state.password;

  this.email = localStorage.getItem('email');
  this.password = localStorage.getItem('password');

  this.errorMessage = null;
  }

  ngOnInit(): void {


    const that = this;
    fetch(
      "http://localhost:8080/all-friends",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded"
        },
        body:
          "email=" + this.email +
          "&authType=regular" +
          "&password=" + this.password
      }
    ).then(async function (data) {
      data.json().then(async function (data) {

        if (data.message === "Friends attached") {
          that.usersAll = data.usersAll;
        } else {
          // setErrorServerMessage(data.message);
          that.errorMessage = data.message;
        }
      });
    });
  }

  signMeOut() {

    this.router.navigateByUrl('/');
  }

  changePassword() {
    // console.log('change password');
    this.router.navigateByUrl('/change');
  }

  onSelect(user) {

    this.form.get('toEmail').setValue(user.email);

    this.showMessages(user.email);
  }

  showMessages (friendEmail) {
    const that = this;

    fetch(
      "http://localhost:8080/messages-user-and-friend",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded"
        },
        body:
          "userEmail=" + this.email +
          "&friendEmail=" + friendEmail +
          "&authType=regular" +
          "&password=" + this.password
      }
    ).then(async function (data) {
      data.json().then(async function (data) {

        if (data.message === "Messages attached") {
          that.msgsAll = data.msgs;
        } else {
          that.errorMessage = data.message;
        }
      });
    });
  } 

  onSubmit(customerData) {
    this.form.reset();

    const that = this;

    fetch(
      "http://localhost:8080/send-message",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded"
        },
        body:
          "message=" + customerData.toMessage +
          "&messageFromEmail=" + this.email +
          "&messageToEmail=" + customerData.toEmail +
          "&authType=regular" +
          "&password=" + this.password
      }
    ).then(async function (data) {
      data.json().then(async function (data) {
        if (data.message === "Message sent") {
          that.errorMessage = "Message sent successfully.";
          that.showMessages(customerData.toEmail);
        } else {
          that.errorMessage = data.messge;
        }
      });
    });
  }
}

{{errorMessage}}
<div>
  <button (click)="signMeOut()">SIGN OUT</button>
</div>
<button (click)="changePassword()">CHANGE PASSWORD</button>

<p>Friends</p>
<p>Hi {{email}}</p>

<p>
  Send Message
  </p>

  <form [formGroup]="form" (ngSubmit)="onSubmit(form.value)">
 
    <div>
      <label for="toEmail">
         Email
      </label>
      <input id="toEmail" type="email" formControlName="toEmail">
    </div>
  
    <div>
      <label for="toMessage">
        Message
      </label>
      <input id="toMessage" type="text" formControlName="toMessage">
    </div>
  
    <button class="button" type="submit">SEND</button>
  
  </form>

  <li *ngFor="let user of usersAll"
    [class.selected]="user === selectedUser"
    (click)="onSelect(user)">
    <span class="badge">{{user.email}}</span> {{user.firstName}} {{user.lastName}}
  </li>

  <li *ngFor="let msg of msgsAll">
    <div>From: {{msg.messageFromEmail}}    To: {{msg.messageToEmail}}</div>
    <div>
      {{msg.message}}
    </div>
    <div>
      {{msg.sentAt}}
    </div>
</li>

// src/components/Profile.vue
<template>
<div>

<div>
 {{errorMessage}}
</div>

 <button v-on:click="signMeOut">SIGN OUT</button>
  <button v-on:click="changePassword">CHANGE PASSWORD</button>

<h2>Friends</h2>
<h3>Hi {{email}}</h3>

<p>
  Send Message
  </p>

<form id="app" @submit="onSubmit">
  
  <p>
    <label for="toEmail">Email</label>
    <input type="email" name="toEmail" id="toEmail" v-model="toEmail">
  </p>

  <p>
    <label for="toMessage">Message</label>
    <input type="text" name="toMessage" id="toMessage" v-model="toMessage">
  </p>

  <p>
    <input type="submit" value="SEND">  
  </p>

</form>

    <ul>
      <li v-for="user in usersAll" @click="onSelect(user)">
          <span class="badge">{{user.email}}</span> {{user.firstName}} {{user.lastName}}
      </li>
    </ul>

    <ul>
      <li v-for="msg in msgsAll">
        <div>From: {{msg.messageFromEmail}}    To: {{msg.messageToEmail}}</div>
        <div>
        {{msg.message}}
        </div>
        <div>
        {{msg.sentAt}}
        </div>
    </li>
    </ul>



</div>
</template>

<script>

export default {
  name: 'Profile',
    data() {
        return {
            email: '',
            password: '',
            toEmail: '',
            toMessage: '',
            errorMessage: null,
            usersAll: [],
            msgsAll: []
        }
    },
    mounted: function () {

        this.email = localStorage.getItem('email')
        this.password = localStorage.getItem('password')


        if (this.email == null || this.password == null) {
            this.$router.push('/')
        }

        const that = this;
        fetch(
        "http://localhost:8080/all-friends",
        {
            method: "POST",
            headers: {
            "Content-Type": "application/x-www-form-urlencoded"
            },
            body:
            "email=" + this.email +
            "&authType=regular" +
            "&password=" + this.password
        }
        ).then(async function (data) {
        data.json().then(async function (data) {

            if (data.message === "Friends attached") {
            that.usersAll = data.usersAll;
            } else {
            // setErrorServerMessage(data.message);
            that.errorMessage = data.message;
            }
        });
        });

    },
    methods: {
        signMeOut: function() {
            localStorage.clear();
            this.$router.push('/')
        }, 
        changePassword: function() {
        this.$router.push('/change')
        },
        onSelect(user) {
            this.toEmail = user.email;
            this.showMessages(user.email)

        },
        onSubmit:function(e) {

            e.preventDefault();

            const that = this;

            fetch(
            "http://localhost:8080/send-message",
            {
                method: "POST",
                headers: {
                "Content-Type": "application/x-www-form-urlencoded"
                },
                body:
                "message=" + this.toMessage +
                "&messageFromEmail=" + this.email +
                "&messageToEmail=" + this.toEmail +
                "&authType=regular" +
                "&password=" + this.password
            }
            ).then(async function (data) {
            data.json().then(async function (data) {
                if (data.message === "Message sent") {
                that.errorMessage = "Message sent successfully.";
                that.showMessages(that.toEmail);
                } else {
                that.errorMessage = data.messge;
                }
            });
            });
        },
        showMessages (friendEmail) {
            const that = this;

            fetch(
            "http://localhost:8080/messages-user-and-friend",
            {
                method: "POST",
                headers: {
                "Content-Type": "application/x-www-form-urlencoded"
                },
                body:
                "userEmail=" + this.email +
                "&friendEmail=" + friendEmail +
                "&authType=regular" +
                "&password=" + this.password
            }
            ).then(async function (data) {
            data.json().then(async function (data) {

                if (data.message === "Messages attached") {
                that.msgsAll = data.msgs;
                } else {
                that.errorMessage = data.message;
                }
            });
            });
        }
    }
    }
</script>
