// src/app/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { FormBuilder } from '@angular/forms';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent implements OnInit {

  form;
  errorMessage;
  email;
  password;
  firstName;
  lastName;
  passwordConfirm;

  constructor(
    private router: Router,
    private formBuilder: FormBuilder
  ) { 
    this.email = localStorage.getItem('email');
    this.password = localStorage.getItem('password');

    this.form = this.formBuilder.group({
      firstName: '',
      lastName: '',
      email: '',
      password: '',
      passwordConfirm: ''
    })
  }

  ngOnInit(): void {
    if (this.email !== null && this.password !== null) {
      this.router.navigateByUrl('/profile');
    }
  }

  goToLogin() {
    this.router.navigate(['/']);
  }


  onSubmit(customerData) {

    this.firstName = customerData.firstName.trim();
    this.lastName = customerData.lastName.trim();
    this.email = customerData.email.trim();
    this.password = customerData.password.trim();
    this.passwordConfirm = customerData.passwordConfirm.trim();
    
    if (
      (this.firstName === "") ||
      (this.lastName === "") ||
      (this.email === "") ||
      (this.password === "") ||
      (this.passwordConfirm === "")
    ) {
      this.errorMessage = "All fields are required. Please fill all of them.";
      return;
    }

    if (this.password !== this.passwordConfirm) {
      this.errorMessage = "Passwords don't match.";
      return;
    }

    const that = this;

    fetch(
      "http://localhost:8080/add-user",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded"
        },
        body:
          "firstName=" +
          this.firstName +
          "&lastName=" +
          this.lastName +
          "&email=" +
          this.email +
          "&password=" +
          this.password +
          "&authType=regular"

      }
    ).then(async function(data) {
      data.json().then(async function(data) {
        if (data.message === "User Created") {
          that.errorMessage = data.message;

          localStorage.setItem('email', that.email);
          localStorage.setItem('password', that.password);

          that.router.navigateByUrl('/profile');

        } else {
          that.errorMessage =  data.message ;
        }
      });
    });
  }
}

<h2>Friends</h2>
<h3>We are glad you are going to become Friends User</h3>
<h3>Please Register</h3>
 
 <form [formGroup]="form" (ngSubmit)="onSubmit(form.value)">
 
   <div>
     <label for="firstName">
        First Name
     </label>
     <input id="firstName" type="text" formControlName="firstName">
   </div>
 
   <div>
     <label for="lastName">
       Last Name
     </label>
     <input id="lastName" type="text" formControlName="lastName">
   </div>

   <div>
    <label for="email">
       Email
    </label>
    <input id="email" type="email" formControlName="email">
  </div>

  <div>
    <label for="password">
      Password
    </label>
    <input id="password" type="password" formControlName="password">
  </div>

  <div>
    <label for="passwordConfirm">
      Password (again)
    </label>
    <input id="passwordConfirm" type="password" formControlName="passwordConfirm">
  </div>

   <button class="button" type="submit">Register</button>
 
 </form>
 <button (click)="goToLogin()">Cancel</button>

 <div>
 {{errorMessage}}
 </div>

// src/components/Register.vue
<template>
<div>
<h2>Friends</h2>
<h3>We are glad you are going to become Friends User</h3>
<h3>Please Register</h3>

<form id="app" @submit="onSubmit">

  <p>
    <label for="firstName">First Name</label>
    <input type="text" name="firstName" id="firstName" v-model="firstName">
  </p>

  <p>
    <label for="lastName">Last Name</label>
    <input type="text" name="lastName" id="lastName" v-model="lastName">
  </p>
  
  <p>
    <label for="email">Email</label>
    <input type="email" name="email" id="email" v-model="email">
  </p>

  <p>
    <label for="password">Password</label>
    <input type="password" name="password" id="password" v-model="password">
  </p>

  <p>
    <label for="passwordConfirm">Password (again)</label>
    <input type="password" name="passwordConfirm" id="passwordConfirm" v-model="passwordConfirm">
  </p>

  <p>
    <input type="submit" value="Register">  
  </p>

</form>
 <button v-on:click="goToLogin">Cancel</button>

<div>
 {{errorMessage}}
</div>

</div>
</template>

<script>

export default {
  name: 'Register',
    data() {
    return {
      errorMessage: "",
      email:"",
      password:"",
      firstName: "",
      lastName: "",
      passwordConfirm: ""
    }
  },
  mounted: function () {

    this.email = localStorage.getItem('email')
    this.password = localStorage.getItem('password')


    if (this.email != null && this.password != null) {
        this.$router.push('/profile')
    }
},
  methods: {
    goToLogin: function() {
      this.$router.push('/')
    },
    onSubmit:function(e) {

      e.preventDefault();

      this.firstName = this.firstName.trim();
      this.lastName = this.lastName.trim();
      this.email = this.email.trim();
      this.password = this.password.trim();
      this.passwordConfirm = this.passwordConfirm.trim();

      if (
        (this.firstName === "") ||
        (this.lastName === "") ||
        (this.email === "") ||
        (this.password === "") ||
        (this.passwordConfirm === "")
      ) {
        this.errorMessage = "All fields are required. Please fill all of them.";
        return;
      }

      if (this.password !== this.passwordConfirm) {
        this.errorMessage = "Passwords don't match.";
        return;
      }

      const that = this;

      fetch(
        "http://localhost:8080/add-user",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/x-www-form-urlencoded"
          },
          body:
            "firstName=" +
            this.firstName +
            "&lastName=" +
            this.lastName +
            "&email=" +
            this.email +
            "&password=" +
            this.password +
            "&authType=regular"

        }
      ).then(async function(data) {
        data.json().then(async function(data) {
          if (data.message === "User Created") {
            that.errorMessage = data.message;

            localStorage.setItem('email', that.email);
            localStorage.setItem('password', that.password);

            that.$router.push('/profile')

          } else {
            that.errorMessage =  data.message ;
          }
        });
      });
    }
  }
}
</script>
