// src/app/reset-password/reset-password.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { FormBuilder } from '@angular/forms';

@Component({
  selector: 'app-reset-password',
  templateUrl: './reset-password.component.html',
  styleUrls: ['./reset-password.component.css']
})
export class ResetPasswordComponent implements OnInit {

  form;
  errorMessage;
  email;
  password;
  passwordConfirm;
  token;

  constructor(
    private router: Router,
    private formBuilder: FormBuilder
  ) { 
    this.email = localStorage.getItem('email');
    this.password = localStorage.getItem('password');

    this.form = this.formBuilder.group({
      email: '',
      password: '',
      passwordConfirm: ''
    })
  }

  ngOnInit(): void {
    if (this.email !== null && this.password !== null) {
      this.router.navigateByUrl('/profile');
    }

    this.token = this.router.parseUrl(this.router.url).queryParams.token;
    if (this.token !== null && this.token !== undefined && this.token !== "") {
      this.errorMessage = "Please select new password.";
    } else {
      this.errorMessage = "Url is tempered";
    }

  }


  goToLogin() {
    this.router.navigate(['/']);
  }

  onSubmit(customerData) {
    this.password = customerData.password.trim();
    this.passwordConfirm = customerData.passwordConfirm.trim();

    const that = this;

    if (this.password.length >= 5 && this.password === this.passwordConfirm) {

      fetch(
        "http://localhost:8080/reset-password",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/x-www-form-urlencoded"
          },
          body:
            "password=" +
            this.password +
            "&token=" +
            this.token
        }
      ).then(async function(data) {
        data.json().then(async function(data) {
          if (data.message === "Password successfully reset") {
            that.errorMessage = "Password updated successfully.";
          } else {
            that.errorMessage = data.message;

          }
        });
      });
    } else {
      this.errorMessage = "Password should be 5 characters long and match.";
    }
  }

}

<h2>Friends</h2>
<h3>Forgot Password</h3>
 
 <form [formGroup]="form" (ngSubmit)="onSubmit(form.value)">

   <div>
    <label for="password">
       Password
    </label>
    <input id="password" type="password" formControlName="password">
  </div>
  <div>
    <label for="passwordConfirm">
       Password (again)
    </label>
    <input id="passwordConfirm" type="password" formControlName="passwordConfirm">
  </div>

   <button class="button" type="submit">RESET PASSWORD</button>
 
 </form>
 <button (click)="goToLogin()">Back to Login</button>

 <div>
 {{errorMessage}}
 </div>

// src/components/ResetPassword.vue
<template>
<div>
<h2>Friends</h2>
<h3>Forgot Password</h3>

<form id="app" @submit="onSubmit">


  <p>
    <label for="password">Password</label>
    <input type="password" name="password" id="password" v-model="password">
  </p>

  <p>
    <label for="passwordConfirm">Password (again)</label>
    <input type="password" name="passwordConfirm" id="passwordConfirm" v-model="passwordConfirm">
  </p>

  <p>
    <input type="submit" value="RESET PASSWORD">  
  </p>

</form>
 <button v-on:click="goToLogin">Back to Login</button>

<div>
 {{errorMessage}}
</div>

</div>
</template>

<script>

export default {
  name: 'ResetPassword',
    data() {
    return {
      errorMessage: null,
      email:null,
      password:null,
      passwordConfirm: null,
      token: null
    }
  },
  mounted: function () {

    this.email = localStorage.getItem('email')
    this.password = localStorage.getItem('password')


    if (this.email != null && this.password != null) {
        this.$router.push('/profile')
    }

    // this.token = this.router.parseUrl(this.router.url).queryParams.token;
    this.token = this.$route.query.token;
    if (this.token !== null && this.token !== undefined && this.token !== "") {
      this.errorMessage = "Please select new password.";
    } else {
      this.errorMessage = "Url is tempered";
    }
},
  methods: {
    goToLogin: function() {
      this.$router.push('/')
    },
    onSubmit:function(e) {

    e.preventDefault();

    if (this.password == null || this.passwordConfirm == null) {
        this.errorMessage = "Password should be 5 characters long and match.";
        return;
    }

    this.password = this.password.trim();
    this.passwordConfirm = this.passwordConfirm.trim();

    const that = this;

    if (this.password.length >= 5 && this.password === this.passwordConfirm) {

      fetch(
        "http://localhost:8080/reset-password",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/x-www-form-urlencoded"
          },
          body:
            "password=" +
            this.password +
            "&token=" +
            this.token
        }
      ).then(async function(data) {
        data.json().then(async function(data) {
          if (data.message === "Password successfully reset") {
            that.errorMessage = "Password updated successfully.";
          } else {
            that.errorMessage = data.message;

          }
        });
      });
    } else {
      this.errorMessage = "Password should be 5 characters long and match.";
    }

    }
  }
}
</script>
